-- Historical migration intentionally contains no credential value.
-- Set whatsapp_ai.settings.webhook_token through the secure operator rotation
-- procedure before enabling the production webhook.
